add auto locale switch system and spanish phrases
Qbox-project/qb-adminmenu pull request #8
Opened 2023-02-24 20:28 UTC by buddizer

**Describe Pull request**
add auto locale switch system and spanish phrases

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

2023-02-24 20:30 UTC, BerkieBb approved these changes

2023-02-25 15:25 UTC, Manason approved these changes

2023-02-25 15:26 UTC, Manason requested changes

2023-02-25 15:26 UTC, Manason commented on fxmanifest.lua
> +version '1.0.1'
```suggestion
version '1.0.0'
```

We're not versioning yet.

2023-02-26 18:23 UTC, Manason approved these changes

2023-02-26 18:25 UTC, merged